name: Roth E. Conrad
favicon: null
layout_spectrum: 0.39894
typography_spectrum: 0.8010993271600455
title: I am.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#503f49'
    - '#cd6b57'
    - '#735e65'
    - '#d4926b'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
