name: Roth E. Conrad
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8010993271600455
title: I am.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0e7083'
    - '#473522'
    - '#fcb66d'
    - '#22c2d6'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
