name: Roth E. Conrad
favicon: null
layout_spectrum: 0.62713
typography_spectrum: 0.8010993271600455
title: I am.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bab8c6'
    - '#444444'
    - '#808088'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
