name: Roth E. Conrad
favicon: null
layout_spectrum: 0.62713
typography_spectrum: 0.8010993271600455
title: I am.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b6d6b'
    - '#ae9795'
    - '#040000'
    - '#8e040a'
    - '#40281f'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
